app/pathogen/arbovirus/dashboard/ArboStudyPopup.tsx
app/pathogen/sarscov2/dashboard/(map)/SarsCov2StudyPopup.tsx

Resolves #11
Here's a screenshot of what the both the Serotracker modal and the Arbotracker modal look like after the change.

Corrected "Atibody Target" to "Antibody Target"

---

components/customs/footer.tsx

Resolves #13
After the change:

Fixed the src attribute for the University of Calgary logo

---

app/pathogen/arbovirus/analyze/columns.tsx

The estimate columns links to the source sheet url.

Added estimate id column and sampling dates

---

app/pathogen/arbovirus/analyze/columns.tsx
app/pathogen/arbovirus/analyze/page.tsx
app/pathogen/arbovirus/analyze/recharts.tsx
app/pathogen/arbovirus/dashboard/(map)/MapAndFilters.tsx
app/pathogen/arbovirus/dashboard/ArboStudyPopupContent.tsx
app/pathogen/arbovirus/dashboard/filters.tsx
app/pathogen/arbovirus/dashboard/page.tsx
app/pathogen/arbovirus/layout.tsx
app/pathogen/sarscov2/dashboard/(map)/MapAndFilters.tsx
app/pathogen/sarscov2/dashboard/(map)/SarsCov2StudyPopup.tsx
app/pathogen/sarscov2/dashboard/filters.tsx
components/ui/data-table.tsx
contexts/arbo-context.tsx
contexts/sarscov2-context.tsx
hooks/useMap.ts
utils/translate-util/translate-service.ts

Made a lot of the simpler changes as requested in the duration of the call. There are a few more changes that will be done in quick succession that will be traced with tickets.

Made a bunch of small changes across the application

---

app/pathogen/arbovirus/analyze/recharts.tsx

Updated the graphs to shrink and resize based on how many will display. 
Update the bars and data to filter out when the data is all 0 so that a user can compare just the data they want to see / is available. 
Added the percentage symbol, 
changed text color to black and update the color of the age graph to be a tad bit nicer

Made the visualizations a lot more responsive to changes

---

app/pathogen/arbovirus/dashboard/(map)/MapAndFilters.tsx

Resolves https://github.com/PathoTracker/Pathotracker/issues/89

Corrected colour of Mayaro Virus pins

---

app/pathogen/arbovirus/analyze/columns.tsx

Fixed sorting to actually sort on date instead of alphabetically. 
Handled when dates are not given to instead return N/A.
Closes #78 and #81

Table date fixes

---

components/customs/multi-select.tsx

Resolves #83
The software that makes gifs for me is broken right now so you'll have to go on Vercel yourself if you want to make sure my stuff works, really sorry about that one :sob:

Fixed a bug that was making filter on "Producer: Euroimmun" impossible.

---

app/pathogen/arbovirus/dashboard/filters.tsx

Ordered the country filter drop down to be in alphabetical order.

feat: Order countries alphabetically

---

components/ui/pathogen-map/pathogen-map.tsx

Removed the compass from the navigation menu for map

---

components/ui/data-table.tsx

Moved the download data button.

---

app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
app/pathogen/arbovirus/dashboard/(map)/MapArbovirusFilter.tsx
app/pathogen/arbovirus/dashboard/(map)/MapArbovirusStudySubmissionPrompt.tsx
tailwind.config.js

Resolves #111 and adds the ability to submit a source to us from the front end!

Added Arbovirus Source Submission Popup

---

components/ui/datepicker.tsx

issue 107 bug fix to close calendar modal upon date selection. Will close 107 upon merge

bugfix: calendar modal will close upon date selection

---

app/pathogen/arbovirus/wip/page.tsx
app/pathogen/arbovirus/wip/sections.tsx
components/ui/scroll-section-group/scroll-section-group.tsx
components/ui/scroll-section-group/use-scroll-section-group.tsx

This PR is the first of many that will implement #136.
Here I'm just creating the skeleton of the page I'm going to build on. The really big feature here is the scroll snapping which I have put a detailed explanation of in my own review.
This page is feature flagged off obviously so nobody will be seeing this in production :)

Added skeleton of the new consolidated dashboard + analyze page with scroll snapping.

---

app/pathogen/arbovirus/visualizations/visualizations.tsx
app/pathogen/arbovirus/wip/sections.tsx
app/pathogen/arbovirus/wip/visualizations-section.tsx
utils/referrer-link-util.ts

This PR another PR of many that will implement https://github.com/PathoTracker/Pathotracker/issues/136.
Here, I'm just adding the visualizations to my new consolidated dashboard + analyze page tab.

Added visualizations to the redesigned dashboard + analyze page

---

app/pathogen/arbovirus/wip/page.tsx
app/pathogen/arbovirus/wip/sections.tsx
app/pathogen/arbovirus/wip/visualizations-section.tsx
components/ui/scroll-section-group/scroll-section-group.tsx
components/ui/scroll-section-group/scroll-section.tsx
components/ui/scroll-section-group/use-scroll-section-group.tsx

This is the last PR I'm throwing up for https://github.com/PathoTracker/Pathotracker/issues/136 for the time being.
The scroll was bothering me so I've fixed it up to be a lot better. Feel free to try on vercel!

Made the scrolling on the consolidated dashboard + analyze page more smooth

---

app/pathogen/arbovirus/wip/visualizations-section.tsx

Fixed broken build resulting from https://github.com/PathoTracker/Pathotracker/commit/b08ebbc983d0c957ebcebb779d124e5c6d1a6ace

Fixed build

---

app/pathogen/arbovirus/analyze/page.tsx
app/pathogen/arbovirus/visualizations/visualizations.tsx

Resolves #144. See tickie for more details.

Changed the order of the visualizations on the analyze page

---

app/pathogen/arbovirus/analyze/recharts.tsx
app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
app/pathogen/arbovirus/dashboard/ArboCountryPopUpContent.tsx
app/pathogen/arbovirus/dashboard/ArboStudyPopupContent.tsx
app/pathogen/sarscov2/dashboard/(map)/MapAndFilters.tsx
components/ui/pathogen-map/pathogen-country-highlight-layer.tsx
components/ui/pathogen-map/pathogen-map-layer.tsx
components/ui/pathogen-map/pathogen-map-popup.tsx
components/ui/pathogen-map/pathogen-map.tsx
components/ui/pathogen-map/use-country-highlight-layer.tsx
components/ui/pathogen-map/use-pathogen-map-mouse.ts
lib/bounding-boxes.ts
lib/country-iso-3166-1-alpha-3-codes.ts

Resolves #108. See tickie for more details.

Added country pop-up modal

---

app/pathogen/arbovirus/analyze/recharts.tsx
app/pathogen/arbovirus/dashboard/page.tsx
app/pathogen/arbovirus/visualizations/visualizations.tsx

Resolves #145.
Had to do some extra stuff to move the legend to the bottom because it looked very strange with the legend to the right. The graph still looks very tall but oh well

Changed the graph shown on the dashboard to the "Estimate count by WHO region and arbovirus" graph.

---

app/pathogen/arbovirus/analyze/recharts/change-in-median-seroprevalence-over-time-graph.tsx
package-lock.json
package.json

Resolves #171. Fixed the yellow fever chart in the change in median seroprevalence visualization

Fixed the yellow fever chart in the change in median seroprevalence visualization

---

app/page.tsx
components/customs/arboStats.tsx
components/customs/header.tsx
components/ui/navigation-menu.tsx

Inspext element: select any phone

Made header and landing page responsive

---

app/pathogen/arbovirus/dashboard/(map)/arbo-map-cluster-utils.tsx

Resolved #215

---

app/about/about-our-data/sponsors.tsx
app/about/faq/page.tsx
app/about/layout.tsx
app/about/the-team/page.tsx
components/ui/navigation-sidebar/navigation-sidebar.tsx

Made about page responsive

---

app/layout.tsx
app/pathogen/arbovirus/dashboard/(map)/MapArbovirusFilter.tsx
app/pathogen/arbovirus/dashboard/(table)/columns.tsx
app/pathogen/arbovirus/dashboard/(visualizations)/change-in-median-seroprevalence-over-time-graph.tsx
app/pathogen/arbovirus/dashboard/(visualizations)/split-bar-chart.tsx
app/pathogen/arbovirus/dashboard/(visualizations)/visualizations-section.tsx
app/pathogen/arbovirus/dashboard/ArboBanner.tsx
app/pathogen/arbovirus/dashboard/filters.tsx
app/pathogen/arbovirus/dashboard/page.tsx
components/ui/data-table/data-table.tsx
hooks/useIsLargeScreen.ts

There are still many issues that will just take a lot more planning and involevment to solve. Especially with the visualizations and data table. Idk if I am just being silly and there is an easy way to solve it but either way have thrown a little disclaimer on there. 
It still kind of usable but we will need to make design changes across the website and it will take more time and desiging. Let me know if there is something that looks too bad and I have to fix it (other than the viz cause they are actually asses and do not comply)

Made the dashboards responsive

---

app/globals.css
app/pathogen/arbovirus/dashboard/(map)/arbo-map-cluster-utils.tsx
components/ui/pathogen-map/pathogen-map-popup.tsx
lib/detect-browser.ts

Resolves #250 
Fixed browser compatibility issues with the map popup.
Firefox:
Chrome:

Fixed browser compatibility issues with the map popup

---

components/customs/header.tsx

Correct the copy of the header given that you can't download a CSV anymore.

Correct the copy of the header given that you can't download a CSV anymore.

---

app/about/faq/page.tsx
app/layout.tsx
app/page.tsx
app/pathogen/arbovirus/dashboard/(map)/MapShadingLegend.tsx
app/pathogen/arbovirus/dashboard/ArboBanner.tsx
app/pathogen/arbovirus/dashboard/filters.tsx
app/pathogen/arbovirus/dashboard/page.tsx

Made some changes based on feedback from the team

---

app/about/the-team/page.tsx

Final touches to the "SeroTracker Team" page for now. A bit of style changes to the headings.

---

app/layout.tsx
components/customs/header.tsx

Resolves #265 and #276.
Firefox
Chrome

Fixed problems with the header on Chrome

---

app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx
app/pathogen/arbovirus/dashboard/ArboBanner.tsx
components/ui/data-table/data-table-column-config.tsx

Fixed the "Download CSV" button in the arbo banner.

---

components/ui/data-table/data-table-column-configurations/data-table-link-button-column-configuration.tsx

Added better error handling for URLs in the data table.

---

components/ui/data-table/data-table-standard-row.tsx
components/ui/data-table/data-table.tsx

Fixed cutoff bug in the data table

---

app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
app/pathogen/arbovirus/dashboard/(map)/arbo-map-cluster-utils.tsx
app/pathogen/sarscov2/dashboard/(map)/SarsCov2Map.tsx
cache/sarscov2.ts
components/ui/pathogen-map/pathogen-map-layer.tsx
components/ui/pathogen-map/pathogen-map.tsx

Added estimate clustering to the SarsCov2 map

---

app/pathogen/sarscov2/dashboard/filters.tsx
contexts/pathogen-context/pathogen-contexts/sc2-context.tsx
hooks/sarscov2/use-sars-cov2-data.tsx
lib/gbd-regions.ts

Fixed a bug with the SC2Tracker filters and a minor bug with the Gbd Superregions. Resolves #374

Fixed a bug with the SC2Tracker filters and a minor bug with the Gbd Superregions

---

app/pathogen/arbovirus/dashboard/(map)/country-highlight-layers/esm-country-highlight-layer.tsx
app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx
components/ui/data-table/data-table-expanded-row-content.tsx
components/ui/data-table/data-table.tsx
components/ui/pathogen-map/country-highlight-layers/data-point-present-layer.tsx

Added a button to view an estimate on the map for ArboTracker

Added a button to view an estimate on the map for ArboTracker

---

app/app-header-and-main.tsx
app/layout.tsx
app/pathogen/arbovirus/arbotracker-help-modal-content.tsx
app/pathogen/arbovirus/dashboard/(map)/use-arbovirus-map-customization-modal.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx
app/pathogen/sarscov2/dashboard/(map)/use-sars-cov-2-map-customization-modal.tsx
components/customs/help-modal-pagination/help-modal-paginator.tsx
components/ui/modal/customization-modal/customization-modal-content.tsx
components/ui/modal/modal-header.tsx
components/ui/modal/modal.tsx
contexts/help-modal-provider.tsx
contexts/theme-provider.tsx

New design for the ArboTracker help modal.

New design for the ArboTracker help modal.

---

app/pathogen/arbovirus/dashboard/(visualizations)/change-in-median-seroprevalence-over-time-graph.tsx
app/pathogen/mers/dashboard/(visualizations)/camel-population-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/median-seroprevalence-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/reported-event-summary-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-who-region/animal-cases-summary-by-who-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-who-region/human-cases-summary-by-who-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-who-region/human-deaths-summary-by-who-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-who-region/seroprevalence-summary-by-who-region.tsx
app/pathogen/mers/dashboard/(visualizations)/visualizations-section.tsx
components/customs/visualizations/split-time-bucketed-bar-chart.tsx

Cleaned up the code for the WHO region summary visualization in MERSTracker.

Cleaned up the code for the WHO region summary visualization in MERSTracker.

---

app/pathogen/generic-pathogen-dashboard-page.tsx
app/pathogen/mers/dashboard/(visualizations)/median-seroprevalence-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-who-region/seroprevalence-summary-by-who-region.tsx
components/customs/visualizations/split-bar-chart.tsx
components/customs/visualizations/split-time-bucketed-bar-chart.tsx
hooks/useIsLargeScreen.ts

Fixed the anchor on the `/dashboard#MAP` type links.

Fixed the anchor on the `/dashboard#MAP` type links.

---

components/customs/visualizations/split-time-bucketed-bar-chart.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-context.tsx

Fixed the country filter for MERSTracker

Fixed the country filter for MERSTracker

---

app/pathogen/mers/dashboard/(visualizations)/summary-by-region.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-summary-by-region-visualization-page-config.tsx

Added country level breakdowns for MERSTracker in the main visualizations section.

Added country level breakdowns for MERSTracker in the main visualizations section.

---

components/ui/pathogen-map/map-customize-button.tsx
contexts/pathogen-context/pathogen-contexts/sarscov2/modelled-sarscov2-seroprevalence-context/data-filtering.tsx

Made the modelled seroprevalence graph for SC2Tracker only include general population estimates.

Made the modelled seroprevalence graph for SC2Tracker only include general population estimates.

---

app/pathogen/sarscov2/dashboard/(table)/sars-cov-2-data-table.tsx
app/pathogen/sarscov2/dashboard/(visualizations)/modelled-seroprevalence-by-who-region/use-modelled-seroprevalence-by-who-region-customization-modal.tsx
app/pathogen/sarscov2/dashboard/(visualizations)/number-of-infections-at-midpoint-by-gbd-region.tsx
components/customs/dropdown/dropdown.tsx
components/customs/visualizations/line-chart.tsx
components/ui/calendar.tsx
components/ui/modal/modal.tsx
contexts/pathogen-context/pathogen-contexts/sarscov2/modelled-sarscov2-seroprevalence-context.tsx
contexts/pathogen-context/pathogen-contexts/sarscov2/modelled-sarscov2-seroprevalence-context/data-filtering.tsx

Allow which data points are included in the SC2Tracker seroprevalence modelling to be modified.

Allow which data points are included in the SC2Tracker seroprevalence modelling to be modified.

---

app/pathogen/mers/dashboard/(map)/animal-mers-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-seroprevalence-summary-by-region.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-summary-by-region-visualization-page-config.tsx

Added Seperate MERSTracker graphs for human and animal events

Added Seperate MERSTracker graphs for human and animal events

---

app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/camels-per-capita-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/total-camel-population-layer.tsx
app/pathogen/mers/dashboard/(map)/mers-map.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx

Set up country outlines in MERSTracker

Set up country outlines in MERSTracker

---

app/app-header-and-main.tsx
app/pathogen/arbovirus/arbotracker-help-modal-content.tsx

Enabled the ArboTracker help modal.

Enabled the ArboTracker help modal.

---

app/pathogen/mers/dashboard/(table)/mers-cases-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx
app/pathogen/mers/dashboard/(visualizations)/median-viral-positive-prevalence-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/visualizations/visualization-page-config.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-summary-by-region-visualization-page-config.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-context.tsx

Made the MERSTracker data table and the visualizations accomodate human vs animal seroprevalence data

Made the MERSTracker data table and the visualizations accomodate human vs animal seroprevalence data

---

app/pathogen/mers/dashboard/(visualizations)/estimates-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-cases-summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-cases-summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-deaths-summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-seroprevalence-summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/visualizations-section.tsx
app/pathogen/mers/dashboard/filters.tsx
app/pathogen/mers/visualizations/visualization-page-config.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-estimates-by-region-visualization-page-config.tsx
components/customs/visualizations/split-time-bucketed-bar-chart.tsx
lib/utils.ts

Created the "Estimates by Region" visualization

Created the "Estimates by Region" visualization

---

app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx
components/ui/data-table/data-table.tsx

Added more estimate fields to the MERS estimate tables

Added more estimate fields to the MERS estimate tables

---

app/pathogen/mers/dashboard/(map)/animal-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/mers-map.tsx
app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
gql/graphql.ts
gql/json/schema.json

Accomodating the new animal types.

Accomodating the new animal types.

---

app/pathogen/arbovirus/arbotracker-help-modal-content.tsx

Updated dimensions on `ArboTrackerHelpModalImage0009.png`

Updated dimensions on `ArboTrackerHelpModalImage0009.png`

---

codegen.ts
gql/graphql.ts
gql/json/schema.json

Related to the new MERS primary estimate API typedef draft.
https://github.com/serotracker/iit-backend-v2/pull/60

Codegenned with new MERS primary estimate API draft

---

app/pathogen/arbovirus/dashboard/(map)/arbo-country-pop-up-content.tsx
app/pathogen/arbovirus/dashboard/(map)/arbovirus-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/animal-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/animal-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/mers-country-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/mers-fao-animal-event-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/mers-fao-human-event-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/filters.tsx
app/pathogen/sarscov2/dashboard/(map)/sars-cov-2-country-pop-up-content.tsx
app/pathogen/sarscov2/dashboard/(map)/sars-cov-2-estimate-pop-up-content.tsx
components/ui/pathogen-map/map-pop-up/generic-map-pop-up.tsx
components/ui/pathogen-map/map-pop-up/map-pop-up-alternate-configuration.tsx
components/ui/pathogen-map/pathogen-map-popup.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-context.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-data-filtering.tsx

Added subestimates in the estimate popup

Added subestimates in the estimate popup

---

app/pathogen/mers/dashboard/(map)/animal-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/animal-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(visualizations)/estimate-breakdown-table/estimate-breakdown-table.tsx
app/pathogen/mers/dashboard/filters.tsx
components/ui/pathogen-map/map-pop-up/map-pop-up-alternate-configuration.tsx
components/ui/pathogen-map/pathogen-map-popup.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-context.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-data-filtering.tsx

POC for new MERSTracker subestimate filtering (using sex as a test field)

POC for new MERSTracker subestimate filtering (using sex as a test field)

---

app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(visualizations)/estimate-breakdown-table/estimate-breakdown-table.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-context.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-data-filtering.tsx

Extended the MERSTracker new filter POC to age group, animal species, and test used

Extended the MERSTracker new filter POC to age group, animal species, and test used

---

app/pathogen/mers/dashboard/(visualizations)/estimate-breakdown-table/estimate-breakdown-table.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-estimate-summary-by-who-region-and-field-page-config.tsx

Added estimate table breakdowns by animal sample frames and specimen types

Added estimate table breakdowns by animal sample frames and specimen types

---

app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx

Fixed the expanded row statement in MERSTracker.

Fixed the expanded row statement in MERSTracker.

---

app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-viral-positive-prevalence-by-region.tsx

Fixed the confidence intervals on the tooltips on the estimates by region visualization

Fixed the confidence intervals on the tooltips on the estimates by region visualization

---

contexts/pathogen-context/pathogen-contexts/mers/mers-data-filtering.tsx

Fixed MERSTracker country filtering.

Fixed MERSTracker country filtering.

---

app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(table)/camel-population-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-cases-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx
app/pathogen/mers/dashboard/(table)/use-mers-data-table-data.tsx

Hiding empty tables from MERSTracker.

Hiding empty tables from MERSTracker.

---

app/pathogen/mers/dashboard/(map)/animal-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/animal-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-viral-positive-prevalence-by-region.tsx
components/ui/pathogen-map/map-pop-up/generic-map-pop-up.tsx

Improved the tooltip on the estimates by region visualization.

Improved the tooltip on the estimates by region visualization.

---

app/pathogen/mers/dashboard/(visualizations)/estimates-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-estimates-by-region-visualization-page-config.tsx

Made a step at improving the empty data situation with the estimates by region graph for MERSTracker.

Made a step at improving the empty data situation with the estimates by region graph for MERSTracker.

---

app/pathogen/mers/dashboard/(map)/country-highlight-layers/helpers.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-reported-animal-cases-map-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-reported-human-cases-map-layer.tsx
app/pathogen/mers/dashboard/(map)/mers-country-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/mers-map.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-cluster-properties.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-data-points.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-paint.tsx
app/pathogen/mers/dashboard/(table)/camel-population-data-table.tsx
app/pathogen/mers/dashboard/(table)/use-mers-data-table-data.tsx
components/ui/pathogen-map/pathogen-map-popup.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-context.tsx
lib/utils.ts

The start of a MERS event map layer

The start of a MERS event map layer

---

app/pathogen/mers/dashboard/(map)/human-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx

Completed the colour set for the MERSTracker fields.

Completed the colour set for the MERSTracker fields.

---

app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
components/ui/data-table/data-table-expanded-row-content.tsx
components/ui/data-table/data-table.tsx
components/ui/pathogen-map/map-pop-up/map-pop-up-alternate-configuration.tsx
components/ui/pathogen-map/map-pop-up/subestimate-table.tsx

Added subestimates to the MERSTracker data table.

Added subestimates to the MERSTracker data table.

---

app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx
app/pathogen/mers/dashboard/filters.tsx
components/customs/filters/available-filters.tsx

Polish some of the terminology and filters in MERSTracker.

Polish some of the terminology and filters in MERSTracker.

---

app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx
components/customs/filters/available-filters.tsx
components/customs/filters/coloured-checkbox-filter.tsx
components/customs/filters/filter-section.tsx
components/customs/filters/grouped-coloured-checkbox-filter.tsx
contexts/pathogen-context/pathogen-contexts/mers/map-customizations-context.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-context.tsx

Synced up the MERSTracker checkbox filters with the map customization settings.

Synced up the MERSTracker checkbox filters with the map customization settings.

---

app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-cluster-properties.tsx
app/pathogen/mers/dashboard/(visualizations)/median-seroprevalence-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/median-viral-positive-prevalence-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-seroprevalence-summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-viral-positive-prevalence-by-region.tsx
gql/graphql.ts
gql/json/schema.json

Fixed the TODOs in the prevalence over time visualizations and start using actual sampling start and end dates.

Fixed the TODOs in the prevalence over time visualizations and start using actual sampling start and end dates.

---

app/pathogen/mers/dashboard/(map)/country-highlight-layers/camels-per-capita-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-reported-animal-cases-map-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-reported-human-cases-map-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/total-camel-population-layer.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx
app/pathogen/mers/dashboard/(table)/mers-data-table.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-summary-by-region-visualization-page-config.tsx
components/customs/dropdown/dropdown.tsx
components/customs/filters/filter-tooltip.tsx
components/customs/generic-tooltip.tsx
components/ui/data-table/data-table.tsx

Better tooltips for describing FAO Empres-i data. Improved legend free text entries for countries with black outlines.

Better tooltips for describing FAO Empres-i data. Improved legend free text entries for countries with black outlines.

---

app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(table)/genomic-sequencing-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx

Added genomic information to the main MERSTracker data table.

Added genomic information to the main MERSTracker data table.

---

app/pathogen/mers/visualizations/visualization-page-config/use-estimates-by-region-visualization-page-config.tsx

Fixed a tiny bug with the 95% CI dropdown in MERSTracker.

Fixed a tiny bug with the 95% CI dropdown in MERSTracker.

---

app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/use-estimates-by-region-legend-props.tsx

Added improved colour highlighting with the legend on the 95% CI graph in MERSTracker.

Added improved colour highlighting with the legend on the 95% CI graph in MERSTracker.

---

components/customs/header.tsx

Added the SeroTracker logo to the dashboard header

Added the SeroTracker logo to the dashboard header

---

components/customs/header.tsx

Added a link in the header to the original SC2Tracker.

Added a link in the header to the original SC2Tracker.

---

app/pathogen/mers/dashboard/(table)/genomic-sequencing-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx

A few tiny fixes and tweaks to our MERSTracker data tables (the genomic data table especially)

A few tiny fixes and tweaks to our MERSTracker data tables (the genomic data table especially)

---

app/about/faq/faq-accordion.tsx
app/about/faq/page.tsx
app/about/faq/text.tsx

Added MERSTracker FAQ section.

Added MERSTracker FAQ section.

---

app/pathogen/mers/dashboard/(map)/mers-map-study-submission-prompt.tsx
app/pathogen/mers/dashboard/(map)/mers-map.tsx

Added MERS study submission prompt to MERSTracker.

Added MERS study submission prompt to MERSTracker.

---

app/about/faq/text.tsx
app/pathogen/arbovirus/arbotracker-citations.tsx
app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx
app/pathogen/arbovirus/dashboard/ArboBanner.tsx
components/ui/data-table/data-table.tsx
contexts/toast-provider.tsx

Added the new ArboTracker citation to the Lancet DOI.

Added the new ArboTracker citation to the Lancet DOI.

---

app/pathogen/arbovirus/arbotracker-citations.tsx
app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx
app/pathogen/arbovirus/visualizations/visualization-page-config.tsx
components/ui/data-table/data-table.tsx

Added a citation column to the CSV file download for ArboTracker.

Added a citation column to the CSV file download for ArboTracker.

---

app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx
components/ui/data-table/data-table.tsx
components/ui/pathogen-map/use-pathogen-map-mouse.ts
package-lock.json
package.json

MERS Estimate Data Table Redesign

MERS Estimate Data Table Redesign

---

app/pathogen/arbovirus/dashboard/filters.tsx

Fixed the pediatric age group filter in ArboTracker.

Fixed the pediatric age group filter in ArboTracker.

---

app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx

Added age minimum and age maximum to the downloaded CSV for ArboTracker.

Added age minimum and age maximum to the downloaded CSV for ArboTracker.

---

app/pathogen/mers/dashboard/(map)/animal-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/animal-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx

Re-ordered the fields on the estimate map pop-up for MERSTracker.

Re-ordered the fields on the estimate map pop-up for MERSTracker.

---

components/ui/pathogen-map/pathogen-map.tsx
contexts/map-style-provider.tsx
contexts/pathogen-context/pathogen-context.tsx

Added the `MapStyleProvider`.

---

app/page.tsx
app/pathogen/arbovirus/dashboard/arbo-banner.tsx
app/pathogen/mers/dashboard/mers-banner.tsx
app/serotracker-introduction.tsx

Updated the copy of the landing page to get ready for the MERSTracker release

Updated the copy of the landing page to get ready for the MERSTracker release

---

app/pathogen/arbovirus/dashboard/arbo-banner.tsx
app/pathogen/mers/dashboard/mers-banner.tsx
components/customs/dashboard-top-banner.tsx

Added the date of the last major data update to the banner for MERSTracker.

Added the date of the last major data update to the banner for MERSTracker.

---

app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
app/pathogen/mers/dashboard/(map)/mers-map.tsx
app/pathogen/sarscov2/dashboard/(map)/SarsCov2Map.tsx
components/ui/pathogen-map/event-point.ts
components/ui/pathogen-map/pathogen-map-popup.tsx
components/ui/pathogen-map/pathogen-map.tsx
components/ui/pathogen-map/use-country-highlight-layer.tsx
components/ui/pathogen-map/use-pathogen-map-mouse.ts

Changed the country pop-up to display on hover.

Changed the country pop-up to display on hover.

---

components/customs/dashboard-top-banner.tsx

Fixed the alignment of the top banner buttons

Fixed the alignment of the top banner buttons

---

app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-cluster-properties.tsx
app/pathogen/mers/dashboard/mers-banner.tsx
app/pathogen/sarscov2/dashboard/(map)/SarsCov2Map.tsx
components/ui/pathogen-map/pathogen-map-layer.tsx
components/ui/pathogen-map/pathogen-map.tsx

Updated clustering for the MERSTracker map to cluster a bit less.

Updated clustering for the MERSTracker map to cluster a bit less.

---

app/pathogen/mers/dashboard/(map)/country-highlight-layers/helpers.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/total-camel-population-layer.tsx
contexts/pathogen-context/pathogen-contexts/mers/map-customizations-context.tsx

Changed the default map layer for MERSTracker to be the camel population layer

Changed the default map layer for MERSTracker to be the camel population layer

---

app/pathogen/mers/dashboard/(map)/mers-map.tsx

Added an explanation for the MERSTracker numbers on the map.

Added an explanation for the MERSTracker numbers on the map.

---

app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx

Fixed the columns for viral estimates in MERSTracker.

Fixed the columns for viral estimates in MERSTracker.

---

app/pathogen/mers/dashboard/(visualizations)/visualizations-section.tsx
app/pathogen/mers/dashboard/mers-banner.tsx

Edited the copy of the MERS top banner, changed the order of the visualizations.

Edited the copy of the MERS top banner, changed the order of the visualizations.

---

app/about/about-our-data/page.tsx
app/pathogen/mers/dashboard/mers-banner.tsx

Added a few little notes about study and assay quality around MERSTracker

Added a few little notes about study and assay quality around MERSTracker

---

app/pathogen/mers/dashboard/filters.tsx
components/customs/filters.tsx

Added a little note to the MERSTracker filters.

Added a little note to the MERSTracker filters.

---

app/pathogen/mers/dashboard/(map)/mers-country-pop-up-content.tsx
components/ui/pathogen-map/map-pop-up/pop-up-content-rows/pop-up-content-text-row.tsx

Added prevalence ranges to the MERSTracker country modal.

Added prevalence ranges to the MERSTracker country modal.

---

app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx
app/pathogen/mers/dashboard/(table)/camel-population-data-table.tsx
app/pathogen/mers/dashboard/(table)/genomic-sequencing-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-cases-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx
app/pathogen/sarscov2/dashboard/(table)/sars-cov-2-data-table.tsx
components/ui/data-table/data-table.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-context.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-filter-metadata-context.tsx

Added some notes to the MERSTracker data table and the visualizations when filters are applied.

Added some notes to the MERSTracker data table when filters are applied.

---

app/pathogen/arbovirus/visualizations/visualization-page-config.tsx
app/pathogen/generic-pathogen-visualizations-page.tsx
app/pathogen/mers/visualizations/visualization-page-config.tsx
app/pathogen/sarscov2/visualizations/visualization-page-config.tsx
components/customs/visualizations/recharts-visualization.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-filter-metadata-context.tsx

Added a footnote to the MERSTracker visualizations when filters have been applied.

Added a footnote to the MERSTracker visualizations when filters have been applied.

---

app/pathogen/generic-pathogen-dashboard-page.tsx
app/pathogen/mers/dashboard/merstracker-between-map-and-data-section-component.tsx
app/pathogen/mers/dashboard/page.tsx

Added the WHO map disclaimer to MERSTracker (It's currently only in the landing page).

Added the WHO map disclaimer to MERSTracker (It's currently only in the landing page).

---

app/app-header-and-main.tsx
app/pathogen/arbovirus/dashboard/arbo-banner.tsx
app/pathogen/mers/dashboard/mers-banner.tsx
app/pathogen/mers/dashboard/merstracker-between-map-and-data-section-component.tsx
components/customs/dashboard-top-banner.tsx
components/customs/header.tsx

Added additional navigation options to the top banner for MERSTracker and ArboTracker.

Added additional navigation options to the top banner for MERSTracker and ArboTracker.

---

app/about/about-our-data/page.tsx
app/pathogen/mers/dashboard/mers-banner.tsx

Added a little note to MERSTracker that explains that the database isn't comprehensive.

Added a little note to MERSTracker that explains that the database isn't comprehensive.

---

app/pathogen/sarscov2/dashboard/(map)/sars-cov-2-estimate-pop-up-content.tsx

Added some new information to the SC2Tracker estimate popup.

Added some new information to the SC2Tracker estimate popup.

---

app/pathogen/mers/dashboard/(map)/country-highlight-layers/camels-per-capita-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/helpers.tsx
app/pathogen/mers/dashboard/(table)/use-mers-data-table-data.tsx

Added a bit of clarity to the legend for camels per capita.

Added a bit of clarity to the legend for camels per capita.

---

app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx

A (hopefully) final update to the MERSTracker colours.

A (hopefully) final update to the MERSTracker colours.

---

app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx

Removed the visualization present in the MERS estimates data table.

Removed the visualization present in the MERS estimates data table.

---

app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx

Shortened the estimate ids in the arbovirus data table.

Shortened the estimate ids in the arbovirus data table.

---

contexts/pathogen-context/pathogen-contexts/mers/mers-data-filtering.tsx

Rework to the animal and human specific filters in MERSTracker.

Rework to the animal and human specific filters in MERSTracker.

---

app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
app/pathogen/arbovirus/dashboard/(map)/arbo-country-pop-up-content.tsx
app/pathogen/arbovirus/dashboard/(map)/arbovirus-estimate-pop-up-content.tsx
app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx
app/pathogen/arbovirus/dashboard/(visualizations)/chart-arbovirus-dropdown.tsx
app/pathogen/arbovirus/dashboard/(visualizations)/rechart-utils.ts
app/pathogen/arbovirus/dashboard/(visualizations)/recharts.tsx
app/pathogen/arbovirus/dashboard/(visualizations)/study-count-over-time-by-sample-frame.tsx
app/pathogen/arbovirus/dashboard/filters.tsx
components/customs/filters/available-filters.tsx
contexts/pathogen-context/pathogen-contexts/arbovirus/arbo-context.tsx
gql/graphql.ts
gql/json/schema.json
tailwind.config.js

Arbovirus data update for October 6th 2024.

Arbovirus data update for October 6th 2024.

---

app/pathogen/mers/dashboard/filters.tsx

Fixed a bug with the functionality of the animal species filter in MERSTracker.

Fixed a bug with the functionality of the animal species filter in MERSTracker.

---

app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx

Added Geographic Scope to the MERSTracker Estimate Modal.

Added Geographic Scope to the MERSTracker Estimate Modal.

---

app/pathogen/mers/dashboard/(map)/mers-country-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/mers-map.tsx
app/pathogen/mers/dashboard/(table)/mers-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-who-cases-data-table.tsx
app/pathogen/mers/dashboard/(table)/use-mers-data-table-data.tsx
hooks/mers/use-mers-who-case-data.tsx
lib/un-regions.ts

Added a data table for MERS cases as reported by the WHO. Added MERS positive case data to the country popup.

Added a data table for MERS cases as reported by the WHO. Added MERS positive case data to the country popup.

---

app/serotracker-introduction.tsx

Minor typo fix.

---

app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
app/pathogen/arbovirus/dashboard/(map)/arbo-country-pop-up-content.tsx
app/pathogen/arbovirus/dashboard/(map)/arbovirus-estimate-pop-up-content.tsx
app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx
app/pathogen/arbovirus/dashboard/(visualizations)/chart-arbovirus-dropdown.tsx
app/pathogen/arbovirus/dashboard/(visualizations)/rechart-utils.ts
app/pathogen/arbovirus/dashboard/(visualizations)/recharts.tsx
app/pathogen/arbovirus/dashboard/filters.tsx
components/customs/filters/available-filters.tsx
contexts/pathogen-context/pathogen-contexts/arbovirus/arbo-context.tsx
gql/graphql.ts
gql/json/schema.json
hooks/arbovirus/useArboData.tsx
hooks/arbovirus/useArboFilters.tsx
tailwind.config.js

Added the boilerplate for adding OROV to ArboTracker.

Added the boilerplate for adding OROV to ArboTracker.

---

app/pathogen/arbovirus/dashboard/(map)/arbovirus-estimate-pop-up-content.tsx

Correct the ArboTracker estimate popup text.

Correct the ArboTracker estimate popup text.

---

app/pathogen/mers/visualizations/visualization-page-config/use-summary-by-region-visualization-page-config.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-macro-sample-frames-context.tsx

Changed the default on the summary by region visualization in MERSTracker to be high risk groups.

Changed the default on the summary by region visualization in MERSTracker to be high risk groups.

---

app/pathogen/arbovirus/dashboard/(visualizations)/change-in-median-seroprevalence-over-time-graph.tsx
app/pathogen/mers/dashboard/(map)/animal-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/animal-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-seroprevalence-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/human-mers-viral-estimate-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/mers-country-pop-up-content.tsx
app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(visualizations)/camel-population-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/estimate-breakdown-table/estimate-breakdown-table.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/median-seroprevalence-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/median-viral-positive-prevalence-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/reported-event-summary-over-time.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-cases-summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-cases-summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-deaths-summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-seroprevalence-summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/mers-banner.tsx
components/customs/visualizations/split-time-bucketed-bar-chart.tsx

Added 3 digits after the decimal point to a bunch of numbers in MERSTracker.

Added 3 digits after the decimal point to a bunch of numbers in MERSTracker.

---

app/pathogen/mers/dashboard/(map)/use-mers-map-legend.tsx

Improvements to the MERSTracker collapsible legend.

Improvements to the MERSTracker collapsible legend.

---

app/pathogen/mers/dashboard/mers-banner.tsx

MERSTracker data update 2024-11-08

MERSTracker data update 2024-11-08

---

gql/graphql.ts
gql/json/schema.json

Updated graphql types to remove V2 types from MERSTracker.

Updated graphql types to remove V2 types from MERSTracker.

---

app/pathogen/arbovirus/arbotracker-help-modal-content.tsx
app/pathogen/arbovirus/dashboard/(map)/country-highlight-layers/esm-country-highlight-layer.tsx
app/pathogen/arbovirus/dashboard/(map)/use-arbovirus-map-customization-modal.tsx
app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx
app/pathogen/arbovirus/dashboard/(visualizations)/country-seroprevalence-comparison-scatter-plot.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/helpers.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-reported-animal-cases-map-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-reported-human-cases-map-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-who-human-cases-map-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/total-camel-population-layer.tsx
app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx
app/pathogen/mers/dashboard/(table)/camel-population-data-table.tsx
app/pathogen/mers/dashboard/(table)/genomic-sequencing-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-cases-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-and-viral-estimates-shared-column-configuration.tsx
app/pathogen/mers/dashboard/(table)/mers-who-cases-data-table.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-estimate-summary-by-who-region-and-field-page-config.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-estimates-by-region-visualization-page-config.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-summary-by-region-visualization-page-config.tsx
app/pathogen/sarscov2/dashboard/(map)/use-sars-cov-2-map-customization-modal.tsx
app/pathogen/sarscov2/dashboard/(table)/sars-cov-2-data-table.tsx
app/pathogen/sarscov2/dashboard/(visualizations)/comparing-seroprevalance-positive-cases-and-vaccinations-over-time/use-comparing-seroprevalence-positive-cases-and-vaccinations-over-time-modal.tsx
app/pathogen/sarscov2/visualizations/visualization-page-config.tsx
components/customs/filters/available-filters.tsx
components/ui/pathogen-map/country-highlight-layers/data-point-present-layer.tsx

Changed the term "Country" to "Country or Area" around the dashboards.

Changed the term "Country" to "Country or Area" around the dashboards.

---

app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-who-human-cases-map-layer.tsx

Improved the wording on the total human positive cases layer for MERSTracker.

Improved the wording on the total human positive cases layer for MERSTracker.

---

app/pathogen/mers/visualizations/visualization-page-config.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-filter-metadata-context.tsx

Added a seperate citation for the visualization downloads.

Added a seperate citation for the visualization downloads.

---

app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx
app/pathogen/mers/dashboard/(table)/mers-data-table.tsx

Removed the confirmed MERS cases from WHO from the dashboard.

Removed the confirmed MERS cases from WHO from the dashboard.

---

app/pathogen/mers/dashboard/(table)/genomic-sequencing-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-data-table.tsx

Fix estimate ids for the genomic data table.

Fix estimate ids for the genomic data table.

---

app/pathogen/mers/visualizations/visualization-page-config/use-estimates-by-region-visualization-page-config.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-summary-by-region-visualization-page-config.tsx
components/customs/tooltip-content.tsx

Removed estimates with a sample size of under 5 from the visualizations.

Removed estimates with a sample size of under 5 from the visualizations.

---

app/about/about-our-data/page.tsx
app/about/faq/text.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx
app/pathogen/mers/visualizations/visualization-page-config.tsx

An update to the text on the "About" page.

An update to the text on the "About" page.

---

app/app-header-and-main.tsx
app/pathogen/mers/dashboard/mers-banner.tsx
app/pathogen/mers/merstracker-welcome-modal-content.tsx
components/ui/modal/modal.tsx

Adjusted the disclaimers on the MERSTracker website and added the welcome modal.

Adjusted the disclaimers on the MERSTracker website and added the welcome modal.

---

app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx

Changed the citation for the camel population data.

Changed the citation for the camel population data.

---

app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
app/pathogen/arbovirus/dashboard/(map)/country-highlight-layers/esm-country-highlight-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/camels-per-capita-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-reported-animal-cases-map-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-reported-human-cases-map-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/mers-who-human-cases-map-layer.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/total-camel-population-layer.tsx
app/pathogen/mers/dashboard/(map)/mers-map.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-paint.tsx
app/pathogen/sarscov2/dashboard/(map)/SarsCov2Map.tsx
components/ui/pathogen-map/country-highlight-layers/country-highlight-layer-legend.tsx
components/ui/pathogen-map/country-highlight-layers/data-point-present-layer.tsx
components/ui/pathogen-map/pathogen-map.tsx

Added a tooltip to the legend for the camel population in MERSTracker.

Added a tooltip to the legend for the camel population in MERSTracker.

---

app/about/faq/text.tsx
app/pathogen/arbovirus/dashboard/(table)/arbo-seroprevalence-data-table.tsx
app/pathogen/arbovirus/dashboard/(table)/arbo-viral-prevalence-data-table.tsx
app/pathogen/mers/dashboard/(table)/camel-population-data-table.tsx
app/pathogen/mers/dashboard/(table)/genomic-sequencing-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-cases-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-who-cases-data-table.tsx
app/pathogen/sarscov2/dashboard/(table)/sars-cov-2-data-table.tsx
components/ui/data-table/data-table.tsx

Throwing in a few more references to the data dictionary.

Throwing in a few more references to the data dictionary.

---

app/pathogen/arbovirus/dashboard/(table)/ArboDataTable.tsx
app/pathogen/arbovirus/dashboard/arbo-banner.tsx
app/pathogen/mers/dashboard/(table)/genomic-sequencing-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-seroprevalence-estimate-data-table.tsx
app/pathogen/mers/dashboard/(table)/mers-viral-estimates-data-table.tsx
app/pathogen/mers/dashboard/mers-banner.tsx
app/pathogen/mers/merstracker-citations.tsx
components/customs/dashboard-top-banner.tsx
components/ui/data-table/data-table.tsx
components/ui/pathogen-map/country-highlight-layers/country-highlight-layer-legend.tsx
contexts/pathogen-context/filter-update-steps.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-filter-metadata-context.tsx
contexts/toast-provider.tsx

Improved the MERSTracker citations.

Improved the MERSTracker citations.

---

app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-seroprevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/animal-viral-positive-prevalence-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-seroprevalence-summary-by-region.tsx
app/pathogen/mers/dashboard/(visualizations)/summary-by-region/human-viral-positive-prevalence-by-region.tsx
components/customs/visualizations/split-time-bucketed-bar-chart.tsx
components/ui/modal/modal.tsx

Adding the number of studies included to the MERSTracker bar graph.

Adding the number of studies included to the MERSTracker bar graph.

---

app/pathogen/mers/visualizations/visualization-page-config/use-summary-by-region-visualization-page-config.tsx
components/customs/filters/available-filters.tsx
components/customs/filters/select-filter.tsx
components/customs/select-inner-multiple-command-group.tsx
components/customs/select-inner-single-command-group.tsx
components/customs/select.tsx
components/customs/visualizations/split-time-bucketed-bar-chart.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-macro-sample-frames-context.tsx
gql/graphql.ts
gql/json/schema.json

Added new MERS macro sample frames for the graph.

Added new MERS macro sample frames for the graph.

---

app/pathogen/mers/dashboard/(visualizations)/estimates-by-region.tsx
app/pathogen/mers/dashboard/filters.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-estimates-by-region-visualization-page-config.tsx
components/customs/filters/available-filters.tsx
components/customs/select-inner-multiple-command-group.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-assay-classification-content.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-context.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-data-filtering.tsx

Setup a system for classifying the different assays in MERSTracker.

Setup a system for classifying the different assays in MERSTracker.

---

app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx

Disabled country border highlighting in MERSTracker.

Disabled country border highlighting in MERSTracker.

---

app/pathogen/mers/visualizations/visualization-page-config/use-estimates-by-region-visualization-page-config.tsx

Removed the "Any" option from the forest plot.

Removed the "Any" option from the forest plot.

---

app/pathogen/mers/dashboard/(map)/mers-map.tsx
components/ui/pathogen-map/pathogen-country-highlight-layer.tsx
components/ui/pathogen-map/pathogen-map.tsx
components/ui/pathogen-map/use-country-highlight-layer.tsx

Adjusted the shading around the Halaib Triangle in the MERSTracker Map.

Adjusted the shading around the Halaib Triangle in the MERSTracker Map.

---

app/pathogen/mers/dashboard/(map)/mers-country-pop-up-content.tsx
app/pathogen/mers/dashboard/(visualizations)/estimates-by-region.tsx
app/pathogen/mers/visualizations/visualization-page-config.tsx
app/pathogen/mers/visualizations/visualization-page-config/use-estimates-by-region-visualization-page-config.tsx
components/customs/select-inner-multiple-command-group.tsx
components/ui/pathogen-map/pathogen-map.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-assay-classification-content.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-filter-metadata-context.tsx

Removed human cases from the country modal. Changed estimate forest plot for viral estimates.

Removed human cases from the country modal. Changed estimate forest plot for viral estimates.

---

app/about/about-our-data/page.tsx
app/about/faq/text.tsx
app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
app/pathogen/mers/dashboard/(map)/country-highlight-layers/total-camel-population-layer.tsx
app/pathogen/mers/dashboard/(map)/mers-map.tsx
app/pathogen/mers/dashboard/(map)/use-mers-map-customization-modal.tsx
app/pathogen/mers/dashboard/(table)/mers-data-table.tsx
app/pathogen/mers/dashboard/merstracker-between-map-and-data-section-component.tsx
app/pathogen/sarscov2/dashboard/(map)/SarsCov2Map.tsx
components/customs/generic-tooltip.tsx
components/ui/pathogen-map/pathogen-country-highlight-layer.tsx
components/ui/pathogen-map/pathogen-map.tsx

Using the new MERSTracker camel population map.

Using the new MERSTracker camel population map.

---

app/pathogen/mers/dashboard/(map)/mers-map-study-submission-prompt.tsx

Added a feedback form for MERSTracker.

Added a feedback form for MERSTracker.

---

app/pathogen/mers/dashboard/filters.tsx
components/customs/filters/available-filters.tsx
contexts/pathogen-context/pathogen-contexts/mers/mers-data-filtering.tsx

Added a filter to MERSTracker for positive prevalence.

Added a filter to MERSTracker for positive prevalence.

---

app/app-header-and-main.tsx
app/pathogen/sarscov2/sc2-tracker-welcome-modal-content.tsx
components/ui/modal/modal.tsx

Added The SarsCov2 Welcome Modal with a link to the old dashboard

Added The SarsCov2 Welcome Modal with a link to the old dashboard

---

app/pathogen/sarscov2/dashboard/(map)/map-config.ts
components/ui/pathogen-map/country-highlight-layers/data-point-present-layer.tsx
components/ui/pathogen-map/pathogen-map.tsx
contexts/map-style-provider.tsx

Bandaid to fix the issue where the map is not appearing.

Bandaid to fix the issue where the map is not appearing.

---

components/ui/pathogen-map/country-highlight-layers/data-point-present-layer.tsx

Brought back the country highlight legend

Brought back the country highlight legend

---

app/pathogen/arbovirus/dashboard/(map)/use-arbovirus-map-customization-modal.tsx
components/ui/pathogen-map/pathogen-country-highlight-layer.tsx

Fixing the country highlighting on Sudan part 2

Fixing the country highlighting on Sudan part 2

---

components/ui/pathogen-map/map-aksai-chin-area-layer.tsx
package-lock.json
package.json

Cleaned up console log

---

components/ui/pathogen-map/disputed-border-layer.tsx
components/ui/pathogen-map/pathogen-map.tsx

Fixing the Sudanese border to conform with UN standards.

Fixing the Sudanese border to conform with UN standards.

---

components/ui/pathogen-map/disputed-border-layer.tsx

`console.log` cleanup

---

components/ui/pathogen-map/disputed-border-layer.tsx

Added borders to Aksai Chin

---

app/pathogen/mers/dashboard/(map)/use-mers-map-paint.tsx
components/ui/pathogen-map/disputed-border-layer.tsx

Fixed colours on Aksai Chin
