serotracker/dashboard

- components/customs/header.tsx
> Fix the Serotracker logo dissapearing on page refresh on certain pages such as the map.

- app/globals.css
- app/pathogen/arbovirus/analyze/ArboDataTable.tsx
- app/pathogen/arbovirus/analyze/columns.tsx
- app/pathogen/arbovirus/analyze/nivo-vis.tsx
- app/pathogen/arbovirus/dashboard/(map)/MapAndFilters.tsx
- app/pathogen/sarscov2/analyze/SarsCov2DataTable.tsx
- app/pathogen/sarscov2/dashboard/(map)/MapAndFilters.tsx
- components/customs/header.tsx
- components/customs/multi-select.tsx
- contexts/arbo-context.tsx
- hooks/useMap.ts
- tailwind.config.js
This PR resolves: #33 #29 #32 and then some based on cosmetic things I believe could be improved
- Added a Link button to the Arbotracker table that takes the user to the publication from which said estimate was extracted
- Updated the style of some parts of the table so that it is easier to understand the data and the decimals are not super long
- Updated the logo to link to the landing page
- Improved the styling of the filters to look cleaner and work more intuitively
- Fixed the issue with the data resetting to all data when the filtered data was empty (this was not intuitive and so now the map and visualizations are blank when the filters amount to no data
- Fixed the antibody filter such that it now works for both the map and the data table and successfully filters for antibodies.
> Antibody filter

- app/pathogen/arbovirus/analyze/columns.tsx
- app/pathogen/arbovirus/dashboard/(map)/MapAndFilters.tsx
- app/pathogen/arbovirus/dashboard/ArboStudyPopupContent.tsx
- app/pathogen/arbovirus/dashboard/filters.tsx
- app/pathogen/sarscov2/analyze/columns.tsx
Resolves #53
I didn't bother with the plots since we're going to change those before showing the conference. The name of the property is still `pathogen` in the app, I'm just changing what it's displayed as. If we want to change the name of the property too on like the API and the rest of the front end (I'm not sure if there's a huge amount of value in that though), let's make it a tech debt ticket. I know there's new instances in PRs open right now so I'll probably just make suggestions on their PRs to use the right word as soon as this gets merged. If their stuff gets merged before mine, I'll change it myself.
> Changed instances of "Pathogen/Pathogens" to "Arbovirus/Arboviruses"

- components/ui/data-table.tsx
Resolves https://github.com/PathoTracker/Pathotracker/issues/59
> The Column selection dropdown no longer closes after selecting a column.

- app/pathogen/arbovirus/dashboard/ArboStudyPopupContent.tsx
There is a small bug that came along with switching to the new API I believe where clicking on a record with an empty array for `antibodies` throws because for some reason an empty array is represented as `"[]"` instead of `[]`. This PR is just a quick band-aid to fix this, I'll look into something more permanent.
> Fix bug that causes the modal not to open when `antibodies` is an empty array for the estimate.

- app/pathogen/arbovirus/analyze/ArboDataTable.tsx
- app/pathogen/arbovirus/analyze/columns.tsx
- app/pathogen/sarscov2/analyze/SarsCov2DataTable.tsx
- app/pathogen/sarscov2/analyze/columns.tsx
- components/ui/card-collection/card-collection.tsx
- components/ui/data-table.tsx
- components/ui/data-table/data-table.tsx
- components/ui/data-table/use-data-table-styles.tsx
- components/ui/table.tsx
Resolves #102 and freezes the `estimateId` column to the left of the table on the analysis tab.
> Freezes the `estimateId` column on the analysis tab

- app/pathogen/arbovirus/analyze/page.tsx
- app/pathogen/arbovirus/dashboard/filters.tsx
- app/pathogen/arbovirus/dashboard/page.tsx
- app/pathogen/arbovirus/wip/page.tsx
- app/pathogen/arbovirus/wip/sections.tsx
- app/pathogen/sarscov2/analyze/page.tsx
- app/pathogen/sarscov2/dashboard/(map)/MapAndFilters.tsx
- app/pathogen/sarscov2/dashboard/filters.tsx
- components/ui/scroll-section-group/use-scroll-section-group.tsx
This PR is another PR of many that will implement https://github.com/PathoTracker/Pathotracker/issues/136.
Here, I'm just adding the filters sidebar to my new consolidated dashboard + analyze page tab.
> Added the filters sidebar to the redesigned dashboard + analyze page

- app/pathogen/arbovirus/dashboard/(map)/ArbovirusMap.tsx
- app/pathogen/arbovirus/wip/sections.tsx
This PR another PR of many that will implement https://github.com/PathoTracker/Pathotracker/issues/136.
Here, I'm just adding the map to my new consolidated dashboard + analyze page tab.
> Added the map to the redesigned dashboard + analyze page

- app/pathogen/arbovirus/analyze/ArboDataTable.tsx
- app/pathogen/arbovirus/analyze/page.tsx
- app/pathogen/arbovirus/wip/sections.tsx
- components/ui/data-table/data-table.tsx
This PR another PR of many that will implement https://github.com/PathoTracker/Pathotracker/issues/136.
Here, I'm just adding the table to my new consolidated dashboard + analyze page tab.
> Added the table to the redesigned dashboard + analyze page

- contexts/arbo-context/filter-update-steps/apply-new-selected-filters.tsx
The problem: when a filter is empty, it defaults to yielding true. This makes sense for most of the other filters, but for pathogen specifically this is illogical. So now, if pathogen is empty, we return false for that particular filter (since all the pathogens are preselected as filters). 
To check: go in and deselect all pathogens with any filter combo.
> All pathogens deselected now yields an empty map.

- components/ui/pathogen-map/pathogen-map-layer.tsx
Resolves #168. Reduced minimum cluster size for map clusters from 10 to 2. Looks fine imo.
> Reduced minimum cluster size for map clusters from 10 to 2

- app/pathogen/arbovirus/dashboard/(table)/columns.tsx
Sort by Seroprevelance in the table, and away you go. I'm worried that some of these cases may actually be legit 0.0's and some others may not be, but that is more of a data cleaning question then anything else. I have done as the ticket asks!
Closes #216.
> Made all cases of what would be 0.0 render as N/A.

- app/about/about-our-data/page.tsx
- app/about/faq/text.tsx
- app/about/layout.tsx
- app/pathogen/arbovirus/dashboard/(map)/MapArbovirusStudySubmissionPrompt.tsx
- components/customs/header.tsx
Part of #231. Just some slight copy revisions from the copy document for this page. Nothing too serious :)
I'm also turning the about page on in production in this PR so that we have less to remember to do when we start linking people over to this dashboard.
> Slight revisions on about page copy. Enables "About" page in production.

- components/ui/data-table/use-data-table-styles.tsx
> The estimate id column is only fixed in the table at the lg breakpoint and above (responsive design for mobile)

- app/pathogen/arbovirus/dashboard/(visualizations)/visualization-header.tsx
Resolves #263. Added hover button effects to all the buttons in the visualization header.
> Added hover button effects to all the buttons in the visualization header

- app/pathogen/arbovirus/dashboard/(map)/arbo-map-cluster-utils.tsx
- components/ui/pathogen-map/pathogen-map-layer.tsx
- components/ui/pathogen-map/pathogen-map.tsx
Resolves #269. The map flickers a little bit when the filters change even if the cluster hasn't changed it's data. I think the intent of the original caching code (which was causing this problem) was to remove the flicker and to save generating elements we don't have to. This saves generating elements we don't have to but still has problems with flickering. Production also has problems with flickering, I think we should do something more in-depth to remove that flickering but I'm just fixing the bug for now.
> Fixed the bugs with incorrect data appearing for the clusters.

- contexts/pathogen-context/filter-update-steps/apply-new-selected-filters.tsx
Fixed the sampling end date filter in both ArboTracker and SC2Tracker. Resolves #354
> Fixed the sampling end date filter

- app/pathogen/arbovirus/dashboard/(visualizations)/visualizations-section.tsx
- app/pathogen/arbovirus/visualizations/visualization-page-config.tsx
- app/pathogen/generic-pathogen-visualizations-page.tsx
- app/pathogen/mers/dashboard/(visualizations)/visualizations-section.tsx
- app/pathogen/mers/visualizations/visualization-page-config.tsx
- app/pathogen/sarscov2/dashboard/(visualizations)/modelled-seroprevalence-by-who-region.tsx
- app/pathogen/sarscov2/dashboard/(visualizations)/modelled-seroprevalence-by-who-region/use-modelled-seroprevalence-by-who-region-customization-modal.tsx
- app/pathogen/sarscov2/dashboard/(visualizations)/visualizations-section.tsx
- app/pathogen/sarscov2/visualizations/page.tsx
- app/pathogen/sarscov2/visualizations/visualization-page-config.tsx
- components/customs/visualizations/line-chart-with-best-fit-curve-and-scatter-points.tsx
- components/customs/visualizations/recharts-visualization.tsx
- components/customs/visualizations/visualization-header.tsx
- components/ui/modal/modal.tsx
- contexts/pathogen-context/pathogen-contexts/sarscov2/modelled-sarscov2-seroprevalence-context.tsx
Added a setting to disable and enable scatter points on the modelled seroprevalence graph. Part of resolving #361.
> Added a setting to disable and enable scatter points on the modelled seroprevalence graph.

- app/pathogen/mers/dashboard/(visualizations)/estimate-breakdown-table/estimate-breakdown-table.tsx
Fixed the names of the UN regions in the estimate breakdown table for MERSTracker.
> Fixed the names of the UN regions in the estimate breakdown table for MERSTracker.

- app/pathogen/mers/dashboard/(map)/shared-mers-map-pop-up-variables.tsx
Added whether or not genomic sequencing was done in the MERSTracker estimate popup.
> Added whether or not genomic sequencing was done in the MERSTracker estimate popup.

- app/pathogen/mers/dashboard/(map)/country-highlight-layers/total-camel-population-layer.tsx
Add the "Data unavailable" entry to the legend for the camel population map.
> Add the "Data unavailable" entry to the legend for the camel population map.

- app/pathogen/arbovirus/dashboard/filters.tsx
- app/pathogen/mers/dashboard/(visualizations)/estimates-by-region.tsx
- app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-seroprevalence-by-region.tsx
- app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/animal-viral-positive-prevalence-by-region.tsx
- app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-seroprevalence-by-region.tsx
- app/pathogen/mers/dashboard/(visualizations)/estimates-by-region/human-viral-positive-prevalence-by-region.tsx
- app/pathogen/mers/dashboard/filters.tsx
- components/customs/filters/available-filters.tsx
- components/customs/filters/filter-section.tsx
- components/customs/filters/select-filter.tsx
Sorted countries in the dashboard by their member state name rather than their Alpha Two Code.
> Sorted countries in the dashboard by their member state name rather than their Alpha Two Code.
